### ISSUE TITLE
Frage: DE

### ISSUE THREAD

**Issue by pgruener** [libracore/erpnextswiss#102]
Hallo,

sorry, fürs Anlegen eines Issues dafür; ich habe keinen anderen Weg erkennen können, wie ich in Kontakt treten kann.

Ich wollte wissen, ob Euch Informationen vorliegen, ob **erpnextswiss** bereits (von irgend jemand) außerhalb der Schweiz (z.B. Deutschland) eingesetzt wurde, oder ob es "_hard facts_" gibt, die grundsätzlich dagegen sprechen.

Die Anmerkungen in `Features` in der Readme lesen sich ja schon so, dass es nicht zwingend inkompatibel zu sein scheint (z.B. MT940 und CAMT sind ja in DE auch gängig).

Wäre super, wenn Ihr dazu ein kurzes Feedback hättet. Oder gibt es ansonsten ggf. ein anderes Repo, das ich bislang nicht gefunden habe?

Danke und Gruß
Philipp

**Comment by lasalesi** [comment]
ERPNextSwiss muss nicht zwingen in der Schweiz eingesetzt werden, insbesondere die Bank-Integration nach ISO 20022 ist in ganz Europa anwendbar. Uns sind Nutzer aus Österreich, Deutschland, Italien und Frankreich bekannt, das funktioniert einwandfrei.
