### ISSUE TITLE
Contract DocType wird zerstört

### ISSUE THREAD

**Issue by pgruener** [libracore/erpnextswiss#105]
### Expected behvauour

Bei Installation von erpnextswiss sollten **nur Zusatz**funktionen hinzugefügt werden, nicht aber bestehende Funktionalität zerstört werden.

### Actual behaviour

In der Basis ERPNext Installation ist im **CRM** Modul der DocType **Contract** vorhanden.
Seit der Installation von erpnextswiss konnte ich keine Contracts mehr finden.

Dabei ist mir in der DocType Liste aufgefallen, dass es einen "neuen" Contract DocType im ERPNextSwiss Modul 
gibt.

Nach Deinstallation der App wurde der originale Contract leider auch nicht wieder hergestellt.

**--> Wie können wir den originalen Contract DocType wieder herstellen?**

### Observed in (version)

Aktueller v13 Branch

### Steps to reproduce

In ERPNext v13 Umgebung erpnextswiss v13 Branch installieren

**Comment by lasalesi** [comment]
Die Ursache ist ein Konflikt mit dem Contract Doctype, den Frappe später in ERPNext eingebaut hat. Zerstört wird dabei aber natürlich nichts. Wichtig ist, dass Contract in ERPNextSwiss mit der IT-Domain zusammenhängt: diese Domain muss aktiv sein, damit der Doctype verfügbar ist.

Domäne auswählen -> IT hinzufügen -> Contract ist da.

**Comment by pgruener** [comment]
Wie bekomme ich denn den ERPNext Contract DocType wieder in das System? Er ist ja jetzt weg.. darüber mache ich mir aktuell noch mehr Gedanken, als über den noch nicht genutzten DocType von ERPNextSwiss.

**Comment by pgruener** [comment]
@sabgaby Unfortunately not in a good way.
I uninstalled erpnextswiss, and after the next upgrade (probably dependent of the next "bench migrate") the original DocType was there again.
But all data lost of course.. bad hustle to grab them from the backups... however.

**Comment by pgruener** [comment]
>  The "did a bench migrate and changed the name of the erpnextswiss doctype contract."

Ok, so I expect in an own fork?
