### ISSUE TITLE
Activity/Compatibility Erpnext v14

### ISSUE THREAD

**Issue by joschi36** [libracore/erpnextswiss#108]
Hello, I'm just starting with ERPnext and am interested in this repo.
I currently have the newest version of ERPnext (14.15.0) installed and tried installing this addon.
However, I got some issues with:
- `dynamic_newsletter.py` frappe.email.queue → Just deleted that for testing
- `edi_file.py` frappe.email.queue → remove mail send from python code for testing
- `DocType Expense Claim not found` now I'm hanging at this error. 

I wanted to ask if this repo is still active, as the README.md says:
> ERPNextSwiss is tested against ERPNext v12. There are compatibility branches for v11 (for user who prefer the old desk) and v13 (for daring users).

With v14 out since August, I'm not sure if this is still used. Is it advised to stay at older versions of ERPnext for production? Maybe use v13?

Once I get to know ERPnext a little better, I'm looking forward to contributing to this repo and the ecosystem!

**Comment by sdlly** [comment]
Same status here. @joschi36 have you been able to move forward in the meantime?

**Comment by kuon** [comment]
I am also looking at erpnext for switzerland use. The repository seems active. Do you have an idea of the work involved to support erpnext v14?

**Comment by cgallay** [comment]
Same issue here. @joschi36 or @sdlly did you find any way to make it work with erpnext v14?

**Comment by sdlly** [comment]
@cgallay Thanks for the update. I'll give it a try asap.

**Comment by joschi36** [comment]
Hi @cgallay 

I have abandoned the project of using ERPNext for the moment, I did not find a working solution. But maybe I will try to use the fork of bvisible in my spare time.

**Comment by cgallay** [comment]
@joschi36 out of curiosity which solution did you go for instead of ERPNext?

**Comment by lasalesi** [comment]
The ERPNextSwiss is primarly tested against libracore/frappe and libracore/erpnext fork from ERPNext, which are improved versions for the Swiss market. Both are readily available from github. Simply switch sources and it will work out of the box.

Due to major changes in frappe/erpnext v14 that conflict with local regulatory requirements, we have so far not invested time into compatibility to v14.
