### ISSUE TITLE
Timeline Change to another tab in a doctype

### ISSUE THREAD

**Issue by Parvathy-N-123** [libracore/erpnextswiss#110]
![image](https://user-images.githubusercontent.com/125261445/218427732-b73cf9fd-1003-42a4-9d7a-0b26836b50cd.png)

We want this timeline to appear in a new tab section of a doctype.
Can you please help us?

**For Example**
![image](https://user-images.githubusercontent.com/125261445/218428700-412964e7-be05-4a77-802d-95ae7a2c1e40.png)

We want the timeline to appear on "tests" tab.

**Comment by lasalesi** [comment]
Tab sections are a feature of Frappe v14, and so is the timeline. Please post this at frappe/frappe.
