### ISSUE TITLE
Salary Certificate is the old version

### ISSUE THREAD

**Issue by genesis81** [libracore/erpnextswiss#111]
The Salery Certificate has an old version. 

The new one has the date of birth in field C 

[Lohnausweis.pdf](https://github.com/libracore/erpnextswiss/files/10776929/Lohnausweis.pdf)

**Comment by lasalesi** [comment]
Thanks for the input. This might be a topic for the next hackathon...

**Comment by lasalesi** [comment]
Resolved in #113
