### ISSUE TITLE
ERPNextSwiss not showing up within v15

### ISSUE THREAD

**Issue by swissbyte** [libracore/erpnextswiss#129]
Hello

Is the v15 branch already working?
I have installed the app but its not showing up in the frontend within v15.

Thanks

**Comment by swissbyte** [comment]
Has been solved after creating a custom image for docker.

**Comment by jabertech** [comment]
> Has been solved after creating a custom image for docker.

Hi, can you share the steps you did for this? I am facing difficulty especially at the step using easy-install.py

https://discuss.frappe.io/t/how-to-add-custom-app-to-production-docker-setup/113283/7
https://databyte.ch/2023/11/17/erpnext-fuer-die-schweiz-mit-erpnextswiss/

I tried to follow through both, but without success...Generating Compose File failed
