### ISSUE TITLE
Merge to ERPNext Core?

### ISSUE THREAD

**Issue by rmehta** [libracore/erpnextswiss#17]
Seems you are doing interesting work, why not add it to core and make it available out-of-the-box to everyone with the `regional` module?

https://discuss.erpnext.com/t/automated-bank-reconciliation-in-erpnext/16736/9

**Comment by lasalesi** [comment]
Hi @rmehta,

thanks for your feedback. While there are some parts that might be interesting for the core, the idea is that this is a country localisation module. Most of the features are relevant only in Switzerland (such as tax declarations, HR forms, banking).

**Comment by rmehta** [comment]
country localizations are not in the core. this will get more users and collaborators as you go ahead. Also localizations will get updated along with major releases incase there are design changes.

https://github.com/frappe/erpnext/tree/develop/erpnext/regional

**Comment by vrms** [comment]
> While there are some parts that might be interesting for the core, the idea is that this is a country localisation module. 

the [FullSize](https://discuss.erpnext.com/t/app-erpnext-full-size-view-for-all-e-g-reports-gant-charts-etc/34910/47) view i.e. would probably serve many non-swiss users.

**Comment by lasalesi** [comment]
There is actually a variety of functions used in a broader context, such as the complete bank integration (ISO 20022 with pain and camt are applied across Europe, csv-import now with custom templates can be used worldwide), fullsize and also the upcoming ZUGFeRD integration (Europe)... So I fully agree, it is not a country localisation. And with the release cycles we are bound to keep it separate.

**Comment by mseibert** [comment]
I read the thread and still do not understand why this is not part of the ERPNext core. The situation looks like a lose lose to me.

ERPNext loses as the features are not part of the core. It's not tested by default. And the libracore repo is maintained by only one user.

**Comment by lasalesi** [comment]
> maintained by only one user
This is not true, this repo is maintained by a company, so the same as frappe

> looks like a lose lose
independent of in the core or not, this feature is available to all ERPNext users through the app. So the user does have the functionality and ERPNext profits from having this as well. I wonder why the app store is gone.

> It's not tested by default
I strongly doubt that the frappe core devs are in a position to test this. AFAIK, neither do they have the connections to banks, reference data nor the ISO standard itself. If this should be tested, it is with a company strongly engaged in banking integration. Why not libracore?
As to testing, I would be more than happy if the core team assures proper testing of the core function (refer to the currency bug).

So the actual win-win is to have a great database Framework maintained by Frappe. And business functionality added as an app, well maintained by a company with competences in this particular field. Who loses?

Lastly, the unpredictable release plans of ERPNext makes it almost impossible to have this on a planned good quality level.

**Comment by rmehta** [comment]
I think it’s fair. No one is obliged to contribute and people may or may not contribute based on many reasons. Those who want to contribute will find a way, those who don’t, will find a dozen reasons not to. Each path has its own consequences.

Free software does not mean we are all universally aligned. Such is life!

**Comment by mseibert** [comment]
I can live with that too. Problem is. As soon as the libracore features get replicated in core, your repo is in trouble. I assume it will happen. And the more vibrant the community gets, the more challenging this will become.

**Comment by lasalesi** [comment]
An app is an open source contribution (note that this is even licensed unter AGPL), which as pointed out will optimally cover user/customer needs. Agree with the the concern from mseibert. Issues with the core coming from the merge of some functionality will actually force users who are using this repo (with all features) to switch to a fork from ERPNext.

Closing this topic.
