### ISSUE TITLE
Raiffeisen csv changed (added IBAN Column)

### ISSUE THREAD

**Issue by marpe1** [libracore/erpnextswiss#46]
### Expected behvauour
Read the Data from the csv-file

### Actual behaviour
Please wait, parsing data...

### Observed in (version)
ERPNextSwiss: v0.9.0 (master)

### Steps to reproduce
actual columns in csv-file
IBAN | Booked At | Text | Credit/Debit Amount | Balance | Valuta Date

old and functional csv-file
Booked At | Text | Credit/Debit Amount | Balance | Valuta Date

--

**Comment by lasalesi** [comment]
Confirmed column definition change in the Raiffeisen CSV-export with details.

**Comment by lasalesi** [comment]
Resolved in 5c85b4e
