### ISSUE TITLE
Can't find the App after Install.

### ISSUE THREAD

**Issue by wojosc** [libracore/erpnextswiss#79]
Hello to you!
After downloading and installing the app successfully I can not seem to find it anywhere in the system. What am I missing? Does it have to be activated some where? Wizard required etc?

Thanks

**Comment by lasalesi** [comment]
Once you have installed it using

    $ bench get-app https://github.com/libracore/erpnextswiss.git
    $ bench install-app erpnextswiss

it should be available on the desktop. To check, you can also go to the doctype list and check for e.g. VAT declaration. Is it available under Help > About?

Things that might go wrong:
* since ERPNext V12, there is an issue on the desktop handling which in some cases hides cards. Show/hide cards will show the card but not enable it. Workaround is to reset the desktop cache. 
* access/permission: make sure you have sufficient access for the module

**Comment by wojosc** [comment]
<img width="352" alt="grafik" src="https://user-images.githubusercontent.com/22279621/83727604-a0443400-a645-11ea-9ec8-b6bdd671aed6.png">

I'll have the permission checked and will give response.

Have a great day!

**Comment by lasalesi** [comment]
From the above screen, the app has not been installed (otherwise it will show up). Can you please repeat 

    $ bench install-app erpnextswiss

![grafik](https://user-images.githubusercontent.com/26505250/83804721-d964be80-a6ae-11ea-910a-6c8ec84c0e76.png)

**Comment by wojosc** [comment]
I should do this also from the folder frappe-bench, right?

I just reran that. It just finishes without any real feedback:
<img width="477" alt="grafik" src="https://user-images.githubusercontent.com/22279621/83812227-6f9ee180-a6bb-11ea-91a8-e53acfaf3be3.png">


On bench migrate I get this:
<img width="581" alt="grafik" src="https://user-images.githubusercontent.com/22279621/83812195-644bb600-a6bb-11ea-80d6-a70282e33903.png">

**Comment by lasalesi** [comment]
The above bench screenshot does not correspond to the Help > About screenshot... is it the same system or is it maybe a tenancy issue?

**Comment by lasalesi** [comment]
Turned out to be a multi-tenancy issue. Use 

    $ bench --site site_name install-app erpnextswiss

to install into the desired tenant (site_name, e.g. erp.example.com)

**Comment by wojosc** [comment]
Thank you @lasalesi this worked. I made a PR for your documentation. Maybe that makes sense. I'm excited to explore the app and will give feedback in time.
