### ISSUE TITLE
Desk Page ERPNextSwiss not found error

### ISSUE THREAD

**Issue by jnkue** [libracore/erpnextswiss#85]
Hello 
i installed the app. It shows up under about and I can search for the Doctype ERPNextSwiss Setting, but the module doesn't show up on the desk. 
I get this error message everytime I clean the cache:
![Bildschirmfoto 2020-09-24 um 21 25 21](https://user-images.githubusercontent.com/35902694/94191886-7c378780-feae-11ea-99d7-f8c8c9f6385b.png)

Thanks in advance

**Comment by lasalesi** [comment]
Which version are you using? ERPNextSwiss is tested against ERPNext v12 and Dokos v1 (not v13 beta or v2)...

**Comment by jnkue** [comment]
Sorry my mistake I was running on Frappe v12 but Erpnext 13.
Now with Erpnext 12 it is working perfectly. 
Do you already know when version 13 will be supported ?
