### ISSUE TITLE
How to install app if we use the official docker frappe erpnext container

### ISSUE THREAD

**Issue by tognellap** [libracore/erpnextswiss#91]
Accordiing to the official issue statement bench is not available in the default container.

https://github.com/frappe/frappe_docker/issues/315

What is the way to install it in the docker container.

**Comment by e-sr** [comment]
Hi, did you succed the installation?

**Comment by tognellap** [comment]
Not jet, tried to install bench as a base, but without success. Only docker Container worked, but i have no clou to execute bench command.

**Comment by lasalesi** [comment]
In case the docker image does not provide the bench environment, installation will not work.

You might want to change over to a full virtual image.
